[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 6

#[[main]]
#  identifier = "archive"
#  name = "Archive"
#  url = "archive"
#  weight = 2

[[main]]
  parent = "posts"
  identifier = "slides"
  name = "Get slides"
  url = "slides"
  weight = 3


[[main]]
  parent = "posts"
  identifier = "graphs"
  name = "Get graphs"
  url = "graphs"
  weight = 4
    
[[main]]
  identifier = "posts"
  name = "Free Resources"
  url = "posts"
  weight = 5    

[[main]]
  parent = "posts"
  name = "Blog"
  url = "posts"
  weight = 5

[[main]]
  parent = "posts"
  identifier = "code"
  name = "Get code"
  url = "code"
  weight = 1

#[[main]]
#  identifier = "publication"
#  name = "Publications"
#  url = "publication"
#  weight = 7
 
 [[main]]
  parent = "about"
  name = "My curiculum"
  url = "about/resume"
  weight = 1
  [[main]]
  parent = "about"
  name = "About"
  url = "about/about"
  weight = 2

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 7

  